# Generated by Django 3.1.2 on 2020-10-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlike',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='The date of a like'),
        ),
    ]
