# Generated by Django 3.1.2 on 2020-10-24 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='last_login',
        ),
    ]
